# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_wav2dat.ui'
#
# Created: Tue Mar 10 11:10:09 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(701, 534)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_options = QtGui.QGroupBox(Dialog)
        self.groupBox_options.setObjectName(_fromUtf8("groupBox_options"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_options)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBox_information = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_information.setChecked(True)
        self.checkBox_information.setObjectName(_fromUtf8("checkBox_information"))
        self.gridLayout_3.addWidget(self.checkBox_information, 0, 0, 1, 2)
        self.spinBox = QtGui.QSpinBox(self.groupBox_options)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_3.addWidget(self.spinBox, 0, 3, 1, 1)
        self.checkBox_same_name = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_same_name.setChecked(False)
        self.checkBox_same_name.setObjectName(_fromUtf8("checkBox_same_name"))
        self.gridLayout_3.addWidget(self.checkBox_same_name, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_options)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_options, 4, 0, 1, 5)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.lineEdit_path_to_write = QtGui.QLineEdit(Dialog)
        self.lineEdit_path_to_write.setObjectName(_fromUtf8("lineEdit_path_to_write"))
        self.gridLayout.addWidget(self.lineEdit_path_to_write, 6, 1, 1, 3)
        self.pushButton_path_to_write = QtGui.QPushButton(Dialog)
        self.pushButton_path_to_write.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_path_to_write.setObjectName(_fromUtf8("pushButton_path_to_write"))
        self.gridLayout.addWidget(self.pushButton_path_to_write, 6, 4, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout.addWidget(self.line, 8, 0, 1, 5)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 5)
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_path_to_read = QtGui.QLineEdit(Dialog)
        self.lineEdit_path_to_read.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_path_to_read.setObjectName(_fromUtf8("lineEdit_path_to_read"))
        self.gridLayout.addWidget(self.lineEdit_path_to_read, 0, 1, 1, 3)
        self.line_1 = QtGui.QFrame(Dialog)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.gridLayout.addWidget(self.line_1, 3, 0, 1, 5)
        self.pushButton_path_to_read = QtGui.QPushButton(Dialog)
        self.pushButton_path_to_read.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_path_to_read.setObjectName(_fromUtf8("pushButton_path_to_read"))
        self.gridLayout.addWidget(self.pushButton_path_to_read, 0, 4, 1, 1)
        self.groupBox_information = QtGui.QGroupBox(Dialog)
        self.groupBox_information.setObjectName(_fromUtf8("groupBox_information"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_information)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_information)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_information)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_information)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_information)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_information)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_information)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_file_name = QtGui.QLabel(self.groupBox_information)
        self.label_file_name.setObjectName(_fromUtf8("label_file_name"))
        self.gridLayout_2.addWidget(self.label_file_name, 0, 1, 1, 1)
        self.label_size = QtGui.QLabel(self.groupBox_information)
        self.label_size.setObjectName(_fromUtf8("label_size"))
        self.gridLayout_2.addWidget(self.label_size, 1, 1, 1, 1)
        self.label_number_of_channels = QtGui.QLabel(self.groupBox_information)
        self.label_number_of_channels.setObjectName(_fromUtf8("label_number_of_channels"))
        self.gridLayout_2.addWidget(self.label_number_of_channels, 4, 1, 1, 1)
        self.label_compression = QtGui.QLabel(self.groupBox_information)
        self.label_compression.setObjectName(_fromUtf8("label_compression"))
        self.gridLayout_2.addWidget(self.label_compression, 10, 1, 1, 1)
        self.label_number_of_frames = QtGui.QLabel(self.groupBox_information)
        self.label_number_of_frames.setObjectName(_fromUtf8("label_number_of_frames"))
        self.gridLayout_2.addWidget(self.label_number_of_frames, 5, 1, 1, 1)
        self.label_sample_width = QtGui.QLabel(self.groupBox_information)
        self.label_sample_width.setObjectName(_fromUtf8("label_sample_width"))
        self.gridLayout_2.addWidget(self.label_sample_width, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_information)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_frame_rate = QtGui.QLabel(self.groupBox_information)
        self.label_frame_rate.setObjectName(_fromUtf8("label_frame_rate"))
        self.gridLayout_2.addWidget(self.label_frame_rate, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_information, 2, 0, 1, 3)
        self.pushButtonConvert = QtGui.QPushButton(Dialog)
        self.pushButtonConvert.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonConvert.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonConvert.setObjectName(_fromUtf8("pushButtonConvert"))
        self.gridLayout.addWidget(self.pushButtonConvert, 9, 4, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))
        self.gridLayout.addWidget(self.pushButtonCancel, 9, 3, 1, 1)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Convert .wav to .dat", None))
        self.groupBox_options.setTitle(_translate("Dialog", "Options", None))
        self.checkBox_information.setText(_translate("Dialog", "Export DAT with information", None))
        self.checkBox_same_name.setText(_translate("Dialog", "Use the same name", None))
        self.label_8.setText(_translate("Dialog", "New Sample Rate (pts/s)", None))
        self.label_10.setText(_translate("Dialog", "Save DAT File To:", None))
        self.pushButton_path_to_write.setText(_translate("Dialog", "Search", None))
        self.label.setText(_translate("Dialog", "Load WAV File In:", None))
        self.pushButton_path_to_read.setText(_translate("Dialog", "Search", None))
        self.groupBox_information.setTitle(_translate("Dialog", "Information", None))
        self.label_5.setText(_translate("Dialog", "Number of Frames (#):", None))
        self.label_6.setText(_translate("Dialog", "Sample Width (Bytes):", None))
        self.label_2.setText(_translate("Dialog", "Total Size (Bytes):", None))
        self.label_7.setText(_translate("Dialog", "Compression:", None))
        self.label_3.setText(_translate("Dialog", "Number of Channels (#):", None))
        self.label_9.setText(_translate("Dialog", "File Name:", None))
        self.label_file_name.setText(_translate("Dialog", "Unknown", None))
        self.label_size.setText(_translate("Dialog", "Unknown", None))
        self.label_number_of_channels.setText(_translate("Dialog", "Unknown", None))
        self.label_compression.setText(_translate("Dialog", "Unknown", None))
        self.label_number_of_frames.setText(_translate("Dialog", "Unknown", None))
        self.label_sample_width.setText(_translate("Dialog", "Unknown", None))
        self.label_4.setText(_translate("Dialog", "Sample Rate (Hz):", None))
        self.label_frame_rate.setText(_translate("Dialog", "Unknown", None))
        self.pushButtonConvert.setText(_translate("Dialog", "Convert", None))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel", None))

