# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_wav2dat.ui'
#
# Created: Sun Mar  1 10:00:58 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 534)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_options = QtGui.QGroupBox(Dialog)
        self.groupBox_options.setObjectName("groupBox_options")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_options)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_information = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_information.setChecked(True)
        self.checkBox_information.setObjectName("checkBox_information")
        self.gridLayout_3.addWidget(self.checkBox_information, 0, 0, 1, 2)
        self.spinBox = QtGui.QSpinBox(self.groupBox_options)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 3, 1, 1)
        self.checkBox_same_name = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_same_name.setChecked(False)
        self.checkBox_same_name.setObjectName("checkBox_same_name")
        self.gridLayout_3.addWidget(self.checkBox_same_name, 1, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_options)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_options, 4, 0, 1, 5)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.lineEdit_path_to_write = QtGui.QLineEdit(Dialog)
        self.lineEdit_path_to_write.setObjectName("lineEdit_path_to_write")
        self.gridLayout.addWidget(self.lineEdit_path_to_write, 6, 1, 1, 3)
        self.pushButton_path_to_write = QtGui.QPushButton(Dialog)
        self.pushButton_path_to_write.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_path_to_write.setObjectName("pushButton_path_to_write")
        self.gridLayout.addWidget(self.pushButton_path_to_write, 6, 4, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 5)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 5)
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_path_to_read = QtGui.QLineEdit(Dialog)
        self.lineEdit_path_to_read.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_path_to_read.setObjectName("lineEdit_path_to_read")
        self.gridLayout.addWidget(self.lineEdit_path_to_read, 0, 1, 1, 3)
        self.line_1 = QtGui.QFrame(Dialog)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 3, 0, 1, 5)
        self.pushButton_path_to_read = QtGui.QPushButton(Dialog)
        self.pushButton_path_to_read.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_path_to_read.setObjectName("pushButton_path_to_read")
        self.gridLayout.addWidget(self.pushButton_path_to_read, 0, 4, 1, 1)
        self.groupBox_information = QtGui.QGroupBox(Dialog)
        self.groupBox_information.setObjectName("groupBox_information")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_information)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox_information)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_information)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_information)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_information)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_information)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_information)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_file_name = QtGui.QLabel(self.groupBox_information)
        self.label_file_name.setObjectName("label_file_name")
        self.gridLayout_2.addWidget(self.label_file_name, 0, 1, 1, 1)
        self.label_size = QtGui.QLabel(self.groupBox_information)
        self.label_size.setObjectName("label_size")
        self.gridLayout_2.addWidget(self.label_size, 1, 1, 1, 1)
        self.label_number_of_channels = QtGui.QLabel(self.groupBox_information)
        self.label_number_of_channels.setObjectName("label_number_of_channels")
        self.gridLayout_2.addWidget(self.label_number_of_channels, 4, 1, 1, 1)
        self.label_compression = QtGui.QLabel(self.groupBox_information)
        self.label_compression.setObjectName("label_compression")
        self.gridLayout_2.addWidget(self.label_compression, 10, 1, 1, 1)
        self.label_number_of_frames = QtGui.QLabel(self.groupBox_information)
        self.label_number_of_frames.setObjectName("label_number_of_frames")
        self.gridLayout_2.addWidget(self.label_number_of_frames, 5, 1, 1, 1)
        self.label_sample_width = QtGui.QLabel(self.groupBox_information)
        self.label_sample_width.setObjectName("label_sample_width")
        self.gridLayout_2.addWidget(self.label_sample_width, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_information)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_frame_rate = QtGui.QLabel(self.groupBox_information)
        self.label_frame_rate.setObjectName("label_frame_rate")
        self.gridLayout_2.addWidget(self.label_frame_rate, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_information, 2, 0, 1, 3)
        self.pushButtonConvert = QtGui.QPushButton(Dialog)
        self.pushButtonConvert.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonConvert.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonConvert.setObjectName("pushButtonConvert")
        self.gridLayout.addWidget(self.pushButtonConvert, 9, 4, 1, 1)
        self.pushButtonCancel = QtGui.QPushButton(Dialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 9, 3, 1, 1)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Convert .wav to .dat", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_options.setTitle(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_information.setText(QtGui.QApplication.translate("Dialog", "Export DAT with information", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_same_name.setText(QtGui.QApplication.translate("Dialog", "Use the same name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "New Sample Rate (pts/s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Save DAT File To:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_path_to_write.setText(QtGui.QApplication.translate("Dialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Load WAV File In:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_path_to_read.setText(QtGui.QApplication.translate("Dialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_information.setTitle(QtGui.QApplication.translate("Dialog", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Number of Frames (#):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Sample Width (Bytes):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Total Size (Bytes):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Compression:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Number of Channels (#):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_file_name.setText(QtGui.QApplication.translate("Dialog", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_size.setText(QtGui.QApplication.translate("Dialog", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_number_of_channels.setText(QtGui.QApplication.translate("Dialog", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_compression.setText(QtGui.QApplication.translate("Dialog", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_number_of_frames.setText(QtGui.QApplication.translate("Dialog", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sample_width.setText(QtGui.QApplication.translate("Dialog", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Sample Rate (Hz):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_frame_rate.setText(QtGui.QApplication.translate("Dialog", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonConvert.setText(QtGui.QApplication.translate("Dialog", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

