# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_wav2dat.ui'
#
# Created: Fri May 17 14:43:30 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 450)
        MainWindow.setMinimumSize(QtCore.QSize(550, 450))
        MainWindow.setMaximumSize(QtCore.QSize(553, 450))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_1 = QtGui.QFrame(self.centralwidget)
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 3, 0, 1, 5)
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.groupBox_options = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_options.setObjectName("groupBox_options")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_options)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_information = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_information.setChecked(True)
        self.checkBox_information.setObjectName("checkBox_information")
        self.gridLayout_3.addWidget(self.checkBox_information, 0, 0, 1, 1)
        self.checkBox_same_name = QtGui.QCheckBox(self.groupBox_options)
        self.checkBox_same_name.setChecked(False)
        self.checkBox_same_name.setObjectName("checkBox_same_name")
        self.gridLayout_3.addWidget(self.checkBox_same_name, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_options, 4, 0, 1, 5)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 5)
        self.lineEdit_path_to_read = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_path_to_read.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_path_to_read.setObjectName("lineEdit_path_to_read")
        self.gridLayout.addWidget(self.lineEdit_path_to_read, 0, 1, 1, 3)
        self.lineEdit_path_to_write = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_path_to_write.setObjectName("lineEdit_path_to_write")
        self.gridLayout.addWidget(self.lineEdit_path_to_write, 6, 1, 1, 3)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 5)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)
        self.groupBox_information = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_information.setObjectName("groupBox_information")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_information)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtGui.QLabel(self.groupBox_information)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_information)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_information)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_information)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_information)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_information)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_file_name = QtGui.QLabel(self.groupBox_information)
        self.label_file_name.setObjectName("label_file_name")
        self.gridLayout_2.addWidget(self.label_file_name, 0, 1, 1, 1)
        self.label_size = QtGui.QLabel(self.groupBox_information)
        self.label_size.setObjectName("label_size")
        self.gridLayout_2.addWidget(self.label_size, 1, 1, 1, 1)
        self.label_number_of_channels = QtGui.QLabel(self.groupBox_information)
        self.label_number_of_channels.setObjectName("label_number_of_channels")
        self.gridLayout_2.addWidget(self.label_number_of_channels, 4, 1, 1, 1)
        self.label_compression = QtGui.QLabel(self.groupBox_information)
        self.label_compression.setObjectName("label_compression")
        self.gridLayout_2.addWidget(self.label_compression, 10, 1, 1, 1)
        self.label_number_of_frames = QtGui.QLabel(self.groupBox_information)
        self.label_number_of_frames.setObjectName("label_number_of_frames")
        self.gridLayout_2.addWidget(self.label_number_of_frames, 5, 1, 1, 1)
        self.label_sample_width = QtGui.QLabel(self.groupBox_information)
        self.label_sample_width.setObjectName("label_sample_width")
        self.gridLayout_2.addWidget(self.label_sample_width, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_information)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_frame_rate = QtGui.QLabel(self.groupBox_information)
        self.label_frame_rate.setObjectName("label_frame_rate")
        self.gridLayout_2.addWidget(self.label_frame_rate, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_information, 2, 0, 1, 3)
        self.pushButton_convert = QtGui.QPushButton(self.centralwidget)
        self.pushButton_convert.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_convert.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.gridLayout.addWidget(self.pushButton_convert, 9, 3, 1, 2)
        self.pushButton_path_to_read = QtGui.QPushButton(self.centralwidget)
        self.pushButton_path_to_read.setObjectName("pushButton_path_to_read")
        self.gridLayout.addWidget(self.pushButton_path_to_read, 0, 4, 1, 1)
        self.pushButton_path_to_write = QtGui.QPushButton(self.centralwidget)
        self.pushButton_path_to_write.setObjectName("pushButton_path_to_write")
        self.gridLayout.addWidget(self.pushButton_path_to_write, 6, 4, 1, 1)
        self.pushButton_close = QtGui.QPushButton(self.centralwidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 9, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_WAV = QtGui.QAction(MainWindow)
        self.actionOpen_WAV.setObjectName("actionOpen_WAV")
        self.actionSave_DAT = QtGui.QAction(MainWindow)
        self.actionSave_DAT.setObjectName("actionSave_DAT")
        self.actionWAV2DAT = QtGui.QAction(MainWindow)
        self.actionWAV2DAT.setObjectName("actionWAV2DAT")
        self.actionWAV_Format = QtGui.QAction(MainWindow)
        self.actionWAV_Format.setObjectName("actionWAV_Format")
        self.actionDAT_Format = QtGui.QAction(MainWindow)
        self.actionDAT_Format.setObjectName("actionDAT_Format")
        self.actionAuthor = QtGui.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.menuFile.addAction(self.actionOpen_WAV)
        self.menuFile.addAction(self.actionSave_DAT)
        self.menuAbout.addAction(self.actionAuthor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Load WAV File In:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Save DAT File To:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_options.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_information.setText(QtGui.QApplication.translate("MainWindow", "Export DAT with information", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_same_name.setText(QtGui.QApplication.translate("MainWindow", "Use the same name", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_information.setTitle(QtGui.QApplication.translate("MainWindow", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Number of Frames (#):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Sample Width (Bytes):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Total Size (Bytes):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Compression:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Number of Channels (#):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "File Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_file_name.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_size.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_number_of_channels.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_compression.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_number_of_frames.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_sample_width.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sample Rate (Hz):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_frame_rate.setText(QtGui.QApplication.translate("MainWindow", "Unknown", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_convert.setText(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_path_to_read.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_path_to_write.setText(QtGui.QApplication.translate("MainWindow", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_close.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_WAV.setText(QtGui.QApplication.translate("MainWindow", "Load WAV", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_DAT.setText(QtGui.QApplication.translate("MainWindow", "Convert to DAT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWAV2DAT.setText(QtGui.QApplication.translate("MainWindow", "WAV2DAT", None, QtGui.QApplication.UnicodeUTF8))
        self.actionWAV_Format.setText(QtGui.QApplication.translate("MainWindow", "WAV Format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDAT_Format.setText(QtGui.QApplication.translate("MainWindow", "DAT Format", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAuthor.setText(QtGui.QApplication.translate("MainWindow", "Author", None, QtGui.QApplication.UnicodeUTF8))

