# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_wavy.ui'
#
# Created: Tue Mar 10 11:10:09 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(845, 563)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/images/symbol.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(150, 0))
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.spinBoxStopRecordingAfter = QtGui.QSpinBox(self.widget)
        self.spinBoxStopRecordingAfter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxStopRecordingAfter.setMaximum(3600)
        self.spinBoxStopRecordingAfter.setObjectName(_fromUtf8("spinBoxStopRecordingAfter"))
        self.gridLayout.addWidget(self.spinBoxStopRecordingAfter, 10, 0, 1, 5)
        self.doubleSpinBoxScale = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxScale.setEnabled(False)
        self.doubleSpinBoxScale.setDecimals(1)
        self.doubleSpinBoxScale.setMinimum(1.0)
        self.doubleSpinBoxScale.setMaximum(20.0)
        self.doubleSpinBoxScale.setObjectName(_fromUtf8("doubleSpinBoxScale"))
        self.gridLayout.addWidget(self.doubleSpinBoxScale, 7, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 2, 1, 1)
        self.labelWindowTime = QtGui.QLabel(self.widget)
        self.labelWindowTime.setObjectName(_fromUtf8("labelWindowTime"))
        self.gridLayout.addWidget(self.labelWindowTime, 4, 0, 1, 5)
        self.lsbrlSampleRate = QtGui.QLabel(self.widget)
        self.lsbrlSampleRate.setObjectName(_fromUtf8("lsbrlSampleRate"))
        self.gridLayout.addWidget(self.lsbrlSampleRate, 2, 0, 1, 5)
        self.doubleSpinBoxOffset = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxOffset.setEnabled(False)
        self.doubleSpinBoxOffset.setDecimals(1)
        self.doubleSpinBoxOffset.setMaximum(10.0)
        self.doubleSpinBoxOffset.setSingleStep(0.1)
        self.doubleSpinBoxOffset.setObjectName(_fromUtf8("doubleSpinBoxOffset"))
        self.gridLayout.addWidget(self.doubleSpinBoxOffset, 7, 4, 1, 1)
        self.labelAbout = QtGui.QLabel(self.widget)
        self.labelAbout.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelAbout.setTextFormat(QtCore.Qt.RichText)
        self.labelAbout.setWordWrap(True)
        self.labelAbout.setObjectName(_fromUtf8("labelAbout"))
        self.gridLayout.addWidget(self.labelAbout, 12, 0, 1, 5)
        self.doubleSpinBoxSampleRate = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSampleRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSampleRate.setDecimals(2)
        self.doubleSpinBoxSampleRate.setObjectName(_fromUtf8("doubleSpinBoxSampleRate"))
        self.gridLayout.addWidget(self.doubleSpinBoxSampleRate, 3, 0, 1, 5)
        self.checkBoxAutoScale = QtGui.QCheckBox(self.widget)
        self.checkBoxAutoScale.setEnabled(False)
        self.checkBoxAutoScale.setChecked(True)
        self.checkBoxAutoScale.setObjectName(_fromUtf8("checkBoxAutoScale"))
        self.gridLayout.addWidget(self.checkBoxAutoScale, 7, 0, 1, 1)
        self.labelStopRecordingAfter = QtGui.QLabel(self.widget)
        self.labelStopRecordingAfter.setObjectName(_fromUtf8("labelStopRecordingAfter"))
        self.gridLayout.addWidget(self.labelStopRecordingAfter, 9, 0, 1, 5)
        self.doubleSpinBoxSampleInterval = QtGui.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSampleInterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSampleInterval.setDecimals(3)
        self.doubleSpinBoxSampleInterval.setMinimum(0.001)
        self.doubleSpinBoxSampleInterval.setMaximum(5.0)
        self.doubleSpinBoxSampleInterval.setSingleStep(0.001)
        self.doubleSpinBoxSampleInterval.setProperty("value", 0.01)
        self.doubleSpinBoxSampleInterval.setObjectName(_fromUtf8("doubleSpinBoxSampleInterval"))
        self.gridLayout.addWidget(self.doubleSpinBoxSampleInterval, 1, 0, 1, 5)
        self.labelScale = QtGui.QLabel(self.widget)
        self.labelScale.setObjectName(_fromUtf8("labelScale"))
        self.gridLayout.addWidget(self.labelScale, 6, 0, 1, 5)
        self.spinBoxWindowTime = QtGui.QSpinBox(self.widget)
        self.spinBoxWindowTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxWindowTime.setMinimum(1)
        self.spinBoxWindowTime.setProperty("value", 20)
        self.spinBoxWindowTime.setObjectName(_fromUtf8("spinBoxWindowTime"))
        self.gridLayout.addWidget(self.spinBoxWindowTime, 5, 0, 1, 5)
        self.labelSampleInterval = QtGui.QLabel(self.widget)
        self.labelSampleInterval.setObjectName(_fromUtf8("labelSampleInterval"))
        self.gridLayout.addWidget(self.labelSampleInterval, 0, 0, 1, 5)
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 7, 1, 1, 1)
        self.labelOffset = QtGui.QLabel(self.widget)
        self.labelOffset.setObjectName(_fromUtf8("labelOffset"))
        self.gridLayout.addWidget(self.labelOffset, 7, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuAcqusition = QtGui.QMenu(self.menubar)
        self.menuAcqusition.setObjectName(_fromUtf8("menuAcqusition"))
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName(_fromUtf8("menuTools"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarFile = QtGui.QToolBar(MainWindow)
        self.toolBarFile.setObjectName(_fromUtf8("toolBarFile"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarFile)
        self.toolBarAcquisition = QtGui.QToolBar(MainWindow)
        self.toolBarAcquisition.setObjectName(_fromUtf8("toolBarAcquisition"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarAcquisition)
        self.actionSave = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/save_as.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.actionAbout_Wavy = QtGui.QAction(MainWindow)
        self.actionAbout_Wavy.setObjectName(_fromUtf8("actionAbout_Wavy"))
        self.actionRecord = QtGui.QAction(MainWindow)
        self.actionRecord.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/record.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon5)
        self.actionRecord.setObjectName(_fromUtf8("actionRecord"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon6)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPause = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon7)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionNew = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon8)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionConvert_Wav_to_Dat = QtGui.QAction(MainWindow)
        self.actionConvert_Wav_to_Dat.setObjectName(_fromUtf8("actionConvert_Wav_to_Dat"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAbout_Wavy)
        self.menuAcqusition.addAction(self.actionRecord)
        self.menuAcqusition.addAction(self.actionPause)
        self.menuAcqusition.addAction(self.actionStop)
        self.menuTools.addAction(self.actionConvert_Wav_to_Dat)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAcqusition.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBarFile.addAction(self.actionNew)
        self.toolBarFile.addAction(self.actionOpen)
        self.toolBarFile.addSeparator()
        self.toolBarFile.addAction(self.actionSave)
        self.toolBarFile.addAction(self.actionSave_As)
        self.toolBarAcquisition.addAction(self.actionRecord)
        self.toolBarAcquisition.addAction(self.actionPause)
        self.toolBarAcquisition.addAction(self.actionStop)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Wavy", None))
        self.spinBoxStopRecordingAfter.setSuffix(_translate("MainWindow", "s", None))
        self.labelWindowTime.setText(_translate("MainWindow", "Window Time (X)", None))
        self.lsbrlSampleRate.setText(_translate("MainWindow", "Sample Rate", None))
        self.labelAbout.setText(_translate("MainWindow", "About:", None))
        self.doubleSpinBoxSampleRate.setSuffix(_translate("MainWindow", "Hz", None))
        self.checkBoxAutoScale.setText(_translate("MainWindow", "Auto", None))
        self.labelStopRecordingAfter.setText(_translate("MainWindow", "Stop Recording After (0 = Manual)", None))
        self.doubleSpinBoxSampleInterval.setSuffix(_translate("MainWindow", "s", None))
        self.labelScale.setText(_translate("MainWindow", " Scale (Y)", None))
        self.spinBoxWindowTime.setSuffix(_translate("MainWindow", "s", None))
        self.labelSampleInterval.setText(_translate("MainWindow", "Sample Interval", None))
        self.label.setText(_translate("MainWindow", "Scale:", None))
        self.labelOffset.setText(_translate("MainWindow", "Offset:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuAcqusition.setTitle(_translate("MainWindow", "Acqusition", None))
        self.menuTools.setTitle(_translate("MainWindow", "Tools", None))
        self.toolBarFile.setWindowTitle(_translate("MainWindow", "toolBar_2", None))
        self.toolBarAcquisition.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+Shift+S", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))
        self.actionAbout_Wavy.setText(_translate("MainWindow", "About Wavy", None))
        self.actionRecord.setText(_translate("MainWindow", "Record", None))
        self.actionRecord.setShortcut(_translate("MainWindow", "Alt+R", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionStop.setShortcut(_translate("MainWindow", "Alt+S", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionPause.setShortcut(_translate("MainWindow", "Alt+P", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N", None))
        self.actionConvert_Wav_to_Dat.setText(_translate("MainWindow", "Convert .wav to .dat", None))

