# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dlg_wav2dat.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 534)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_options = QtWidgets.QGroupBox(Dialog)
        self.groupBox_options.setObjectName("groupBox_options")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_options)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_information = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_information.setChecked(True)
        self.checkBox_information.setObjectName("checkBox_information")
        self.gridLayout_3.addWidget(self.checkBox_information, 0, 0, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_options)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 3, 1, 1)
        self.checkBox_same_name = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_same_name.setChecked(False)
        self.checkBox_same_name.setObjectName("checkBox_same_name")
        self.gridLayout_3.addWidget(self.checkBox_same_name, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_options)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_options, 4, 0, 1, 5)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.lineEdit_path_to_write = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_path_to_write.setObjectName("lineEdit_path_to_write")
        self.gridLayout.addWidget(self.lineEdit_path_to_write, 6, 1, 1, 3)
        self.pushButton_path_to_write = QtWidgets.QPushButton(Dialog)
        self.pushButton_path_to_write.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_path_to_write.setObjectName("pushButton_path_to_write")
        self.gridLayout.addWidget(self.pushButton_path_to_write, 6, 4, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 5)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 5)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_path_to_read = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_path_to_read.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_path_to_read.setObjectName("lineEdit_path_to_read")
        self.gridLayout.addWidget(self.lineEdit_path_to_read, 0, 1, 1, 3)
        self.line_1 = QtWidgets.QFrame(Dialog)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 3, 0, 1, 5)
        self.pushButton_path_to_read = QtWidgets.QPushButton(Dialog)
        self.pushButton_path_to_read.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton_path_to_read.setObjectName("pushButton_path_to_read")
        self.gridLayout.addWidget(self.pushButton_path_to_read, 0, 4, 1, 1)
        self.groupBox_information = QtWidgets.QGroupBox(Dialog)
        self.groupBox_information.setObjectName("groupBox_information")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_information)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_information)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_information)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_information)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_information)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_information)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_information)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_file_name = QtWidgets.QLabel(self.groupBox_information)
        self.label_file_name.setObjectName("label_file_name")
        self.gridLayout_2.addWidget(self.label_file_name, 0, 1, 1, 1)
        self.label_size = QtWidgets.QLabel(self.groupBox_information)
        self.label_size.setObjectName("label_size")
        self.gridLayout_2.addWidget(self.label_size, 1, 1, 1, 1)
        self.label_number_of_channels = QtWidgets.QLabel(self.groupBox_information)
        self.label_number_of_channels.setObjectName("label_number_of_channels")
        self.gridLayout_2.addWidget(self.label_number_of_channels, 4, 1, 1, 1)
        self.label_compression = QtWidgets.QLabel(self.groupBox_information)
        self.label_compression.setObjectName("label_compression")
        self.gridLayout_2.addWidget(self.label_compression, 10, 1, 1, 1)
        self.label_number_of_frames = QtWidgets.QLabel(self.groupBox_information)
        self.label_number_of_frames.setObjectName("label_number_of_frames")
        self.gridLayout_2.addWidget(self.label_number_of_frames, 5, 1, 1, 1)
        self.label_sample_width = QtWidgets.QLabel(self.groupBox_information)
        self.label_sample_width.setObjectName("label_sample_width")
        self.gridLayout_2.addWidget(self.label_sample_width, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_information)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_frame_rate = QtWidgets.QLabel(self.groupBox_information)
        self.label_frame_rate.setObjectName("label_frame_rate")
        self.gridLayout_2.addWidget(self.label_frame_rate, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_information, 2, 0, 1, 3)
        self.pushButtonConvert = QtWidgets.QPushButton(Dialog)
        self.pushButtonConvert.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonConvert.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonConvert.setObjectName("pushButtonConvert")
        self.gridLayout.addWidget(self.pushButtonConvert, 9, 4, 1, 1)
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 9, 3, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Convert .wav to .dat"))
        self.groupBox_options.setTitle(_translate("Dialog", "Options"))
        self.checkBox_information.setText(_translate("Dialog", "Export DAT with information"))
        self.checkBox_same_name.setText(_translate("Dialog", "Use the same name"))
        self.label_8.setText(_translate("Dialog", "New Sample Rate (pts/s)"))
        self.label_10.setText(_translate("Dialog", "Save DAT File To:"))
        self.pushButton_path_to_write.setText(_translate("Dialog", "Search"))
        self.label.setText(_translate("Dialog", "Load WAV File In:"))
        self.pushButton_path_to_read.setText(_translate("Dialog", "Search"))
        self.groupBox_information.setTitle(_translate("Dialog", "Information"))
        self.label_5.setText(_translate("Dialog", "Number of Frames (#):"))
        self.label_6.setText(_translate("Dialog", "Sample Width (Bytes):"))
        self.label_2.setText(_translate("Dialog", "Total Size (Bytes):"))
        self.label_7.setText(_translate("Dialog", "Compression:"))
        self.label_3.setText(_translate("Dialog", "Number of Channels (#):"))
        self.label_9.setText(_translate("Dialog", "File Name:"))
        self.label_file_name.setText(_translate("Dialog", "Unknown"))
        self.label_size.setText(_translate("Dialog", "Unknown"))
        self.label_number_of_channels.setText(_translate("Dialog", "Unknown"))
        self.label_compression.setText(_translate("Dialog", "Unknown"))
        self.label_number_of_frames.setText(_translate("Dialog", "Unknown"))
        self.label_sample_width.setText(_translate("Dialog", "Unknown"))
        self.label_4.setText(_translate("Dialog", "Sample Rate (Hz):"))
        self.label_frame_rate.setText(_translate("Dialog", "Unknown"))
        self.pushButtonConvert.setText(_translate("Dialog", "Convert"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))


import wavytool.images.rc_wavy_rc