# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_wav2dat.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 450)
        MainWindow.setMinimumSize(QtCore.QSize(550, 450))
        MainWindow.setMaximumSize(QtCore.QSize(553, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_1 = QtWidgets.QFrame(self.centralwidget)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.gridLayout.addWidget(self.line_1, 3, 0, 1, 5)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 9, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.groupBox_options = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_options.setObjectName("groupBox_options")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_options)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_information = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_information.setChecked(True)
        self.checkBox_information.setObjectName("checkBox_information")
        self.gridLayout_3.addWidget(self.checkBox_information, 0, 0, 1, 2)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_options)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 3, 1, 1)
        self.checkBox_same_name = QtWidgets.QCheckBox(self.groupBox_options)
        self.checkBox_same_name.setChecked(False)
        self.checkBox_same_name.setObjectName("checkBox_same_name")
        self.gridLayout_3.addWidget(self.checkBox_same_name, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_options)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox_options, 4, 0, 1, 5)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 8, 0, 1, 5)
        self.lineEdit_path_to_read = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path_to_read.setMinimumSize(QtCore.QSize(300, 0))
        self.lineEdit_path_to_read.setObjectName("lineEdit_path_to_read")
        self.gridLayout.addWidget(self.lineEdit_path_to_read, 0, 1, 1, 3)
        self.lineEdit_path_to_write = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_path_to_write.setObjectName("lineEdit_path_to_write")
        self.gridLayout.addWidget(self.lineEdit_path_to_write, 6, 1, 1, 3)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 5)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 5, 0, 1, 5)
        self.groupBox_information = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_information.setObjectName("groupBox_information")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_information)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_information)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_information)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_information)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_information)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_information)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_information)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_file_name = QtWidgets.QLabel(self.groupBox_information)
        self.label_file_name.setObjectName("label_file_name")
        self.gridLayout_2.addWidget(self.label_file_name, 0, 1, 1, 1)
        self.label_size = QtWidgets.QLabel(self.groupBox_information)
        self.label_size.setObjectName("label_size")
        self.gridLayout_2.addWidget(self.label_size, 1, 1, 1, 1)
        self.label_number_of_channels = QtWidgets.QLabel(self.groupBox_information)
        self.label_number_of_channels.setObjectName("label_number_of_channels")
        self.gridLayout_2.addWidget(self.label_number_of_channels, 4, 1, 1, 1)
        self.label_compression = QtWidgets.QLabel(self.groupBox_information)
        self.label_compression.setObjectName("label_compression")
        self.gridLayout_2.addWidget(self.label_compression, 10, 1, 1, 1)
        self.label_number_of_frames = QtWidgets.QLabel(self.groupBox_information)
        self.label_number_of_frames.setObjectName("label_number_of_frames")
        self.gridLayout_2.addWidget(self.label_number_of_frames, 5, 1, 1, 1)
        self.label_sample_width = QtWidgets.QLabel(self.groupBox_information)
        self.label_sample_width.setObjectName("label_sample_width")
        self.gridLayout_2.addWidget(self.label_sample_width, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_information)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_frame_rate = QtWidgets.QLabel(self.groupBox_information)
        self.label_frame_rate.setObjectName("label_frame_rate")
        self.gridLayout_2.addWidget(self.label_frame_rate, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_information, 2, 0, 1, 3)
        self.pushButton_convert = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_convert.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_convert.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_convert.setObjectName("pushButton_convert")
        self.gridLayout.addWidget(self.pushButton_convert, 9, 3, 1, 2)
        self.pushButton_path_to_read = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_path_to_read.setObjectName("pushButton_path_to_read")
        self.gridLayout.addWidget(self.pushButton_path_to_read, 0, 4, 1, 1)
        self.pushButton_path_to_write = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_path_to_write.setObjectName("pushButton_path_to_write")
        self.gridLayout.addWidget(self.pushButton_path_to_write, 6, 4, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 9, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 550, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen_WAV = QtWidgets.QAction(MainWindow)
        self.actionOpen_WAV.setObjectName("actionOpen_WAV")
        self.actionSave_DAT = QtWidgets.QAction(MainWindow)
        self.actionSave_DAT.setObjectName("actionSave_DAT")
        self.actionWAV2DAT = QtWidgets.QAction(MainWindow)
        self.actionWAV2DAT.setObjectName("actionWAV2DAT")
        self.actionWAV_Format = QtWidgets.QAction(MainWindow)
        self.actionWAV_Format.setObjectName("actionWAV_Format")
        self.actionDAT_Format = QtWidgets.QAction(MainWindow)
        self.actionDAT_Format.setObjectName("actionDAT_Format")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        self.actionAuthor.setObjectName("actionAuthor")
        self.menuFile.addAction(self.actionOpen_WAV)
        self.menuFile.addAction(self.actionSave_DAT)
        self.menuAbout.addAction(self.actionAuthor)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Load WAV File In:"))
        self.label_10.setText(_translate("MainWindow", "Save DAT File To:"))
        self.groupBox_options.setTitle(_translate("MainWindow", "Options"))
        self.checkBox_information.setText(_translate("MainWindow", "Export DAT with information"))
        self.checkBox_same_name.setText(_translate("MainWindow", "Use the same name"))
        self.label_8.setText(_translate("MainWindow", "New Sample Rate (pts/s)"))
        self.groupBox_information.setTitle(_translate("MainWindow", "Information"))
        self.label_5.setText(_translate("MainWindow", "Number of Frames (#):"))
        self.label_6.setText(_translate("MainWindow", "Sample Width (Bytes):"))
        self.label_2.setText(_translate("MainWindow", "Total Size (Bytes):"))
        self.label_7.setText(_translate("MainWindow", "Compression:"))
        self.label_3.setText(_translate("MainWindow", "Number of Channels (#):"))
        self.label_9.setText(_translate("MainWindow", "File Name:"))
        self.label_file_name.setText(_translate("MainWindow", "Unknown"))
        self.label_size.setText(_translate("MainWindow", "Unknown"))
        self.label_number_of_channels.setText(_translate("MainWindow", "Unknown"))
        self.label_compression.setText(_translate("MainWindow", "Unknown"))
        self.label_number_of_frames.setText(_translate("MainWindow", "Unknown"))
        self.label_sample_width.setText(_translate("MainWindow", "Unknown"))
        self.label_4.setText(_translate("MainWindow", "Sample Rate (Hz):"))
        self.label_frame_rate.setText(_translate("MainWindow", "Unknown"))
        self.pushButton_convert.setText(_translate("MainWindow", "Convert"))
        self.pushButton_path_to_read.setText(_translate("MainWindow", "Search"))
        self.pushButton_path_to_write.setText(_translate("MainWindow", "Search"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionOpen_WAV.setText(_translate("MainWindow", "Load WAV"))
        self.actionSave_DAT.setText(_translate("MainWindow", "Convert to DAT"))
        self.actionWAV2DAT.setText(_translate("MainWindow", "WAV2DAT"))
        self.actionWAV_Format.setText(_translate("MainWindow", "WAV Format"))
        self.actionDAT_Format.setText(_translate("MainWindow", "DAT Format"))
        self.actionAuthor.setText(_translate("MainWindow", "Author"))


import wavytool.images.rc_wavy_rc