# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mw_wavy.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from qtpy import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 563)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(150, 0))
        self.widget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBoxStopRecordingAfter = QtWidgets.QSpinBox(self.widget)
        self.spinBoxStopRecordingAfter.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxStopRecordingAfter.setMaximum(3600)
        self.spinBoxStopRecordingAfter.setObjectName("spinBoxStopRecordingAfter")
        self.gridLayout.addWidget(self.spinBoxStopRecordingAfter, 10, 0, 1, 5)
        self.doubleSpinBoxScale = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxScale.setEnabled(False)
        self.doubleSpinBoxScale.setDecimals(1)
        self.doubleSpinBoxScale.setMinimum(1.0)
        self.doubleSpinBoxScale.setMaximum(20.0)
        self.doubleSpinBoxScale.setObjectName("doubleSpinBoxScale")
        self.gridLayout.addWidget(self.doubleSpinBoxScale, 7, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 2, 1, 1)
        self.labelWindowTime = QtWidgets.QLabel(self.widget)
        self.labelWindowTime.setObjectName("labelWindowTime")
        self.gridLayout.addWidget(self.labelWindowTime, 4, 0, 1, 5)
        self.lsbrlSampleRate = QtWidgets.QLabel(self.widget)
        self.lsbrlSampleRate.setObjectName("lsbrlSampleRate")
        self.gridLayout.addWidget(self.lsbrlSampleRate, 2, 0, 1, 5)
        self.doubleSpinBoxOffset = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxOffset.setEnabled(False)
        self.doubleSpinBoxOffset.setDecimals(1)
        self.doubleSpinBoxOffset.setMaximum(10.0)
        self.doubleSpinBoxOffset.setSingleStep(0.1)
        self.doubleSpinBoxOffset.setObjectName("doubleSpinBoxOffset")
        self.gridLayout.addWidget(self.doubleSpinBoxOffset, 7, 4, 1, 1)
        self.labelAbout = QtWidgets.QLabel(self.widget)
        self.labelAbout.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelAbout.setTextFormat(QtCore.Qt.RichText)
        self.labelAbout.setWordWrap(True)
        self.labelAbout.setObjectName("labelAbout")
        self.gridLayout.addWidget(self.labelAbout, 12, 0, 1, 5)
        self.doubleSpinBoxSampleRate = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSampleRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSampleRate.setDecimals(2)
        self.doubleSpinBoxSampleRate.setObjectName("doubleSpinBoxSampleRate")
        self.gridLayout.addWidget(self.doubleSpinBoxSampleRate, 3, 0, 1, 5)
        self.checkBoxAutoScale = QtWidgets.QCheckBox(self.widget)
        self.checkBoxAutoScale.setEnabled(False)
        self.checkBoxAutoScale.setChecked(True)
        self.checkBoxAutoScale.setObjectName("checkBoxAutoScale")
        self.gridLayout.addWidget(self.checkBoxAutoScale, 7, 0, 1, 1)
        self.labelStopRecordingAfter = QtWidgets.QLabel(self.widget)
        self.labelStopRecordingAfter.setObjectName("labelStopRecordingAfter")
        self.gridLayout.addWidget(self.labelStopRecordingAfter, 9, 0, 1, 5)
        self.doubleSpinBoxSampleInterval = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBoxSampleInterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSampleInterval.setDecimals(3)
        self.doubleSpinBoxSampleInterval.setMinimum(0.001)
        self.doubleSpinBoxSampleInterval.setMaximum(5.0)
        self.doubleSpinBoxSampleInterval.setSingleStep(0.001)
        self.doubleSpinBoxSampleInterval.setProperty("value", 0.01)
        self.doubleSpinBoxSampleInterval.setObjectName("doubleSpinBoxSampleInterval")
        self.gridLayout.addWidget(self.doubleSpinBoxSampleInterval, 1, 0, 1, 5)
        self.labelScale = QtWidgets.QLabel(self.widget)
        self.labelScale.setObjectName("labelScale")
        self.gridLayout.addWidget(self.labelScale, 6, 0, 1, 5)
        self.spinBoxWindowTime = QtWidgets.QSpinBox(self.widget)
        self.spinBoxWindowTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxWindowTime.setMinimum(1)
        self.spinBoxWindowTime.setProperty("value", 20)
        self.spinBoxWindowTime.setObjectName("spinBoxWindowTime")
        self.gridLayout.addWidget(self.spinBoxWindowTime, 5, 0, 1, 5)
        self.labelSampleInterval = QtWidgets.QLabel(self.widget)
        self.labelSampleInterval.setObjectName("labelSampleInterval")
        self.gridLayout.addWidget(self.labelSampleInterval, 0, 0, 1, 5)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 7, 1, 1, 1)
        self.labelOffset = QtWidgets.QLabel(self.widget)
        self.labelOffset.setObjectName("labelOffset")
        self.gridLayout.addWidget(self.labelOffset, 7, 3, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAcqusition = QtWidgets.QMenu(self.menubar)
        self.menuAcqusition.setObjectName("menuAcqusition")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBarFile = QtWidgets.QToolBar(MainWindow)
        self.toolBarFile.setObjectName("toolBarFile")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarFile)
        self.toolBarAcquisition = QtWidgets.QToolBar(MainWindow)
        self.toolBarAcquisition.setObjectName("toolBarAcquisition")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBarAcquisition)
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/save_as.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon2)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName("actionOpen")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout_Qt = QtWidgets.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName("actionAbout_Qt")
        self.actionAbout_Wavy = QtWidgets.QAction(MainWindow)
        self.actionAbout_Wavy.setObjectName("actionAbout_Wavy")
        self.actionRecord = QtWidgets.QAction(MainWindow)
        self.actionRecord.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRecord.setIcon(icon5)
        self.actionRecord.setObjectName("actionRecord")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon6)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon7)
        self.actionPause.setObjectName("actionPause")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon8)
        self.actionNew.setObjectName("actionNew")
        self.actionConvert_Wav_to_Dat = QtWidgets.QAction(MainWindow)
        self.actionConvert_Wav_to_Dat.setObjectName("actionConvert_Wav_to_Dat")
        self.actionPrint_graph = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint_graph.setIcon(icon9)
        self.actionPrint_graph.setObjectName("actionPrint_graph")
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPrint_graph)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout_Qt)
        self.menuHelp.addAction(self.actionAbout_Wavy)
        self.menuAcqusition.addAction(self.actionRecord)
        self.menuAcqusition.addAction(self.actionPause)
        self.menuAcqusition.addAction(self.actionStop)
        self.menuTools.addAction(self.actionConvert_Wav_to_Dat)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAcqusition.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBarFile.addAction(self.actionSave_As)
        self.toolBarFile.addAction(self.actionPrint_graph)
        self.toolBarAcquisition.addAction(self.actionRecord)
        self.toolBarAcquisition.addAction(self.actionPause)
        self.toolBarAcquisition.addAction(self.actionStop)
        self.toolBarAcquisition.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wavy"))
        self.spinBoxStopRecordingAfter.setSuffix(_translate("MainWindow", "s"))
        self.labelWindowTime.setText(_translate("MainWindow", "Window Time (X)"))
        self.lsbrlSampleRate.setText(_translate("MainWindow", "Sample Rate"))
        self.labelAbout.setText(_translate("MainWindow", "About:"))
        self.doubleSpinBoxSampleRate.setSuffix(_translate("MainWindow", "Hz"))
        self.checkBoxAutoScale.setText(_translate("MainWindow", "Auto"))
        self.labelStopRecordingAfter.setText(_translate("MainWindow", "Stop Recording After (0 = Manual)"))
        self.doubleSpinBoxSampleInterval.setSuffix(_translate("MainWindow", "s"))
        self.labelScale.setText(_translate("MainWindow", " Scale (Y)"))
        self.spinBoxWindowTime.setSuffix(_translate("MainWindow", "s"))
        self.labelSampleInterval.setText(_translate("MainWindow", "Sample Interval"))
        self.label.setText(_translate("MainWindow", "Scale:"))
        self.labelOffset.setText(_translate("MainWindow", "Offset:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAcqusition.setTitle(_translate("MainWindow", "Acqusition"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.toolBarFile.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.toolBarAcquisition.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionSave_As.setToolTip(_translate("MainWindow", "Save data as file"))
        self.actionSave_As.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt"))
        self.actionAbout_Wavy.setText(_translate("MainWindow", "About Wavy"))
        self.actionRecord.setText(_translate("MainWindow", "Record"))
        self.actionRecord.setToolTip(_translate("MainWindow", "Start recording"))
        self.actionRecord.setShortcut(_translate("MainWindow", "Alt+R"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setToolTip(_translate("MainWindow", "Stop recording"))
        self.actionStop.setShortcut(_translate("MainWindow", "Alt+S"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setToolTip(_translate("MainWindow", "Pause recording"))
        self.actionPause.setShortcut(_translate("MainWindow", "Alt+P"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionConvert_Wav_to_Dat.setText(_translate("MainWindow", "Convert .wav to .dat"))
        self.actionPrint_graph.setText(_translate("MainWindow", "Export graph"))
        self.actionPrint_graph.setToolTip(_translate("MainWindow", "Export graph as image"))
        self.actionPrint_graph.setShortcut(_translate("MainWindow", "Ctrl+E"))

import wavytool.images.rc_wavy_rc
